// Step-3 check (plan §7) against the running dev server, so every save goes through the real
// afterChange hook -> after() path. Test data: 2 PDFs (NCPOR's 43-ISEA call for proposals and a generated
// image-only "scanned" page) and 3 photos from data/photos. They are uploaded once and reused on later runs,
// so no file is uploaded twice and no LLM runs twice for them. One metadata-only event is created and deleted.
// Needs: npm run dev (port 3000), npm run users:test (data/test-users.json), npm run seed
// Run:   npm run check:step3                keeps the test records so you can open them in /admin
//        npm run check:step3 -- --cleanup   deletes them, their R2 files and their chunks
import assert from 'node:assert/strict'
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { sql } from '@payloadcms/db-postgres'
import type { CollectionSlug, Where } from 'payload'
import { getPayload } from 'payload'
import sharp from 'sharp'

import config from '@payload-config'
import { processRecord } from '../../src/pipeline'
import { citedIds, devanagariShare, sentences } from '../../src/pipeline/text'

type Doc = Record<string, any>
const BASE = process.env.APP_BASE_URL || 'http://localhost:3000'
const payload = await getPayload({ config })
const db = (q: ReturnType<typeof sql>) => payload.db.drizzle.execute(q).then((r) => r.rows as Doc[])

// ---- Test data ----

// An A4 page that is only a JPEG, like a scan: no text layer at all.
async function scannedPdf(): Promise<Buffer> {
  const lines = ['SCIENTIFIC REPORT (SCANNED PAGE)', 'Step 3 test page: this text is part of an image.', 'There is no text layer, so the pipeline must', 'flag the file as needs_ocr and not summarise it.']
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="1240" height="1754"><rect width="100%" height="100%" fill="#f3efe4"/>${lines
    .map((l, i) => `<text x="110" y="${220 + i * 70}" font-family="serif" font-size="40" fill="#2a2a2a">${l}</text>`)
    .join('')}</svg>`
  const jpeg = await sharp(Buffer.from(svg)).jpeg({ quality: 60 }).toBuffer()
  const parts: Buffer[] = []
  const offsets: number[] = []
  let size = 0
  const push = (b: Buffer | string) => {
    const buf = typeof b === 'string' ? Buffer.from(b, 'latin1') : b
    parts.push(buf)
    size += buf.length
  }
  const obj = (n: number, dict: string, stream?: Buffer) => {
    offsets[n] = size
    push(`${n} 0 obj\n${dict}\n`)
    if (stream) {
      push('stream\n')
      push(stream)
      push('\nendstream\n')
    }
    push('endobj\n')
  }
  const content = Buffer.from('q 595 0 0 842 0 0 cm /Im0 Do Q')
  push('%PDF-1.4\n')
  obj(1, '<</Type/Catalog/Pages 2 0 R>>')
  obj(2, '<</Type/Pages/Kids[3 0 R]/Count 1>>')
  obj(3, '<</Type/Page/Parent 2 0 R/MediaBox[0 0 595 842]/Resources<</XObject<</Im0 4 0 R>>>>/Contents 5 0 R>>')
  obj(4, `<</Type/XObject/Subtype/Image/Width 1240/Height 1754/ColorSpace/DeviceRGB/BitsPerComponent 8/Filter/DCTDecode/Length ${jpeg.length}>>`, jpeg)
  obj(5, `<</Length ${content.length}>>`, content)
  const xref = size
  push(`xref\n0 6\n0000000000 65535 f \n${offsets.slice(1).map((o) => `${String(o).padStart(10, '0')} 00000 n \n`).join('')}`)
  push(`trailer<</Size 6/Root 1 0 R>>\nstartxref\n${xref}\n%%EOF\n`)
  return Buffer.concat(parts)
}

const stationId = async (name: string) =>
  (await payload.find({ collection: 'stations', where: { name: { equals: name } }, locale: 'en', depth: 0, limit: 1 })).docs[0]?.id

const photo = (file: string) => ({ collection: 'media' as const, file: `data/photos/${file}`, mimeType: 'image/jpeg', expect: 'ready' })
const fixtures = [
  {
    key: 'isea',
    collection: 'reports' as const,
    file: 'data/pdfs/43-ISEA Webpage advertisment.PDF',
    mimeType: 'application/pdf',
    expect: 'ready',
    data: {
      title: 'Invitation for research proposals: 43rd Indian Scientific Expedition to Antarctica',
      report_type: 'other',
      year: 2023,
      region: 'antarctic',
      source_url: 'https://ncpor.res.in/upload/recruitments/43-ISEA%20Webpage%20advertisment.PDF',
      license: 'NCPOR public document (reuse terms not yet verified)',
      credit: 'National Centre for Polar and Ocean Research (NCPOR)',
    },
  },
  {
    key: 'scanned',
    collection: 'reports' as const,
    buffer: await scannedPdf(),
    name: 'step3-scanned-test-page.pdf',
    mimeType: 'application/pdf',
    expect: 'needs_ocr',
    data: { title: 'Scanned-style test page (demo data, step 3 check)', report_type: 'other', license: 'demo data', credit: 'Generated by scripts/step3/check.ts' },
  },
  {
    key: 'bharati',
    ...photo('bharati-station-antarctica/Bharati permanent Antarctic research station.jpg'),
    data: {
      region: 'antarctic',
      stations: [await stationId('Bharati')],
      source_url: 'https://commons.wikimedia.org/wiki/File:Bharati_permanent_Antarctic_research_station.jpg',
      license: 'Public domain',
      credit: 'Unknown author, via Wikimedia Commons',
    },
  },
  {
    key: 'himadri',
    ...photo('himadri-station-svalbard/Indian station 1.JPG'),
    data: {
      region: 'arctic',
      stations: [await stationId('Himadri')],
      source_url: 'https://commons.wikimedia.org/wiki/File:Indian_station_1.JPG',
      license: 'CC BY-SA',
      credit: 'Superchilum, CC BY-SA, via Wikimedia Commons',
    },
  },
  {
    key: 'schirmacher',
    ...photo('schirmacher-oasis/An aerial view of Schirmacher Hills.jpg'),
    data: {
      region: 'antarctic',
      taken_at: '1983-01-15',
      source_url: 'https://commons.wikimedia.org/wiki/File:An_aerial_view_of_Schirmacher_Hills.jpg',
      license: 'CC BY-SA',
      credit: 'Pavan Nair, CC BY-SA, via Wikimedia Commons',
    },
  },
]
type Fixture = (typeof fixtures)[number]

const findExisting = async (fx: Fixture) => {
  const where: Where = fx.collection === 'reports' ? { title: { equals: (fx.data as Doc).title } } : { source_url: { equals: fx.data.source_url } }
  return (await payload.find({ collection: fx.collection, where, locale: 'en', depth: 0, limit: 1 })).docs[0]?.id as number | undefined
}

if (process.argv.includes('--cleanup')) {
  for (const fx of fixtures) {
    const id = await findExisting(fx)
    if (id) await payload.delete({ collection: fx.collection, id }) // S3 plugin deletes the R2 objects, the pipeline hook the chunks
    console.log(`${fx.key}: ${id ? `deleted ${fx.collection}/${id}` : 'not found'}`)
  }
  process.exit(0)
}

// ---- REST helpers (as the staff roles, through the dev server) ----

const creds = JSON.parse(readFileSync('data/test-users.json', 'utf8'))
async function rest(token: string, method: string, url: string, body?: unknown | FormData) {
  const res = await fetch(`${BASE}${url}`, {
    method,
    headers: { Authorization: `JWT ${token}`, ...(body && !(body instanceof FormData) ? { 'Content-Type': 'application/json' } : {}) },
    body: body instanceof FormData ? body : body ? JSON.stringify(body) : undefined,
  })
  const json = await res.json().catch(() => ({}))
  if (!res.ok) throw new Error(`${method} ${url} -> ${res.status} ${JSON.stringify(json).slice(0, 500)}`)
  return json as Doc
}
const login = async (role: string) => (await rest('', 'POST', '/api/users/login', creds[role])).token as string

async function until<T>(what: string, fn: () => Promise<T>, timeoutMs = 300_000): Promise<T> {
  const end = Date.now() + timeoutMs
  for (;;) {
    const v = await fn()
    if (v) return v
    if (Date.now() > end) throw new Error(`timed out waiting for ${what}`)
    await new Promise((r) => setTimeout(r, 2000))
  }
}

const latest = async (collection: string, id: number) =>
  (await payload.findByID({ collection: collection as CollectionSlug, id, draft: true, locale: 'all', depth: 0 })) as Doc
const chunksOf = (collection: string, id: number) =>
  db(sql`select id, locale, position, page, heading, text, published from archive_chunks
         where collection = ${collection} and doc_id = ${String(id)} order by locale, position`)

let passed = 0
async function step(name: string, fn: () => Promise<unknown>) {
  await fn()
  passed++
  console.log(`ok  ${name}`)
}

// ---- Run ----

const editor = await login('editor')
const reviewer = await login('reviewer')
const ids: Record<string, number> = {}
const uploaded: string[] = []
for (const fx of fixtures) {
  const existing = await findExisting(fx)
  if (existing) {
    ids[fx.key] = existing
    continue
  }
  const buffer: Buffer = 'buffer' in fx && fx.buffer ? fx.buffer : readFileSync((fx as Doc).file)
  const form = new FormData()
  form.append('file', new Blob([new Uint8Array(buffer)], { type: fx.mimeType }), 'name' in fx ? fx.name : path.basename(fx.file))
  form.append('_payload', JSON.stringify(fx.data))
  ids[fx.key] = (await rest(editor, 'POST', `/api/${fx.collection}?draft=true`, form)).doc.id
  uploaded.push(`${fx.key} (${buffer.length} bytes)`)
}
console.log(uploaded.length ? `uploaded: ${uploaded.join(', ')}` : 'all test records already exist, nothing uploaded')

const docs: Record<string, Doc> = {}
for (const fx of fixtures) {
  docs[fx.key] = (await until(`${fx.key} to finish processing`, async () => {
    const d = await latest(fx.collection, ids[fx.key])
    return !['queued', 'processing'].includes(d.processing_state) && d
  })) as Doc
}
const { isea, scanned } = docs
const photos = ['bharati', 'himadri', 'schirmacher'].map((k) => docs[k])

await step('the 43-ISEA PDF reaches ready with an English and Hindi summary, every sentence cited', async () => {
  assert.equal(isea.processing_state, 'ready', isea.processing_error)
  assert.equal(isea.page_count, 13)
  assert.equal(isea.ai_generated, true)
  assert.ok(isea.keywords?.length, 'keywords')
  const pageChunkIds = new Set((await chunksOf('reports', isea.id)).filter((c) => c.position > 0).map((c) => Number(c.id)))
  for (const locale of ['en', 'hi']) {
    const text = isea.summary?.[locale]
    assert.ok(text, `summary ${locale}`)
    for (const s of sentences(text)) assert.ok(citedIds(s).length && citedIds(s).every((id) => pageChunkIds.has(id)), `uncited or foreign citation: ${s}`)
  }
  assert.ok(devanagariShare(isea.summary.hi) > 0.6, 'Hindi summary in Devanagari')
})

await step('its chunks carry PDF page numbers and are found by full-text search', async () => {
  const chunks = await chunksOf('reports', isea.id)
  const pages = chunks.filter((c) => c.position > 0)
  assert.ok(pages.length >= 10 && pages.every((c) => c.page >= 1 && c.page <= 13 && c.locale === 'en'))
  const meta = chunks.filter((c) => c.position === 0)
  assert.deepEqual(meta.map((c) => c.locale), ['en', 'hi'], 'one record chunk per locale')
  assert.equal(meta[0].heading, isea.title.en)
  const hits = await db(sql`
    select page, ts_rank(tsv, q) as rank from archive_chunks, websearch_to_tsquery('english', 'helicopter snow vehicles') q
    where collection = 'reports' and doc_id = ${String(isea.id)} and tsv @@ q order by rank desc`)
  assert.ok(hits.length && hits[0].page >= 1, 'search hit with a page')
  const hi = await db(sql`
    select count(*)::int as n from archive_chunks, to_tsquery('simple', 'अंटार्कटिका') q
    where collection = 'reports' and doc_id = ${String(isea.id)} and locale = 'hi' and tsv @@ q`)
  console.log(`    english hit on PDF page ${hits[0].page}; Hindi record chunk matches अंटार्कटिका: ${hi[0].n > 0}`)
})

await step('the scanned PDF lands in needs_ocr: no page chunks, no summary, still findable by title', async () => {
  assert.equal(scanned.processing_state, 'needs_ocr', scanned.processing_error)
  assert.equal(scanned.page_count, 1)
  assert.ok(!scanned.summary?.en && !scanned.summary?.hi)
  const chunks = await chunksOf('reports', scanned.id)
  assert.deepEqual(chunks.map((c) => [c.locale, c.position]), [['en', 0]])
})

await step('each photo gets a caption and alt text in English and Hindi', async () => {
  for (const p of photos) {
    assert.equal(p.processing_state, 'ready', p.processing_error)
    assert.equal(p.ai_generated, true)
    for (const f of ['caption', 'alt']) assert.ok(p[f]?.en && p[f]?.hi, `${p.filename} ${f}`)
    assert.ok(devanagariShare(p.alt.hi) > 0.6 && devanagariShare(p.caption.hi) > 0.6, `${p.filename} Hindi`)
    assert.ok([...p.alt.en].length <= 250 && p.tags?.length)
    const chunks = await chunksOf('media', p.id)
    assert.deepEqual(chunks.map((c) => c.locale), ['en', 'hi'])
    console.log(`    ${p.filename}: ${p.alt.hi}`)
  }
})

await step('re-running processed records calls no LLM and keeps chunk ids (citations stay valid)', async () => {
  const before = (await chunksOf('reports', isea.id)).map((c) => c.id)
  const records: [string, Doc][] = [['reports', isea], ['reports', scanned], ...photos.map((p): [string, Doc] => ['media', p])]
  for (const [collection, d] of records) {
    const r = await processRecord(payload, collection, d.id)
    assert.equal(r.error, undefined)
    assert.equal(r.llm.length, 0, `${collection}/${d.id} called an LLM`)
    assert.equal(r.state, d.processing_state)
  }
  assert.deepEqual((await chunksOf('reports', isea.id)).map((c) => c.id), before)
})

await step('a stale admin form cannot wipe AI output or the state; a real edit clears ai_generated', async () => {
  const url = `/api/reports/${isea.id}?draft=true`
  await rest(editor, 'PATCH', url, { summary: '', keywords: [], processing_state: 'queued', page_count: null })
  let d = await latest('reports', isea.id)
  assert.equal(d.summary.en, isea.summary.en)
  assert.deepEqual(d.keywords, isea.keywords)
  assert.deepEqual([d.processing_state, d.page_count, d.ai_generated], ['ready', 13, true])
  await rest(editor, 'PATCH', url, { keywords: [...isea.keywords, 'edited by staff'] })
  d = await latest('reports', isea.id)
  assert.equal(d.ai_generated, false)
  // Put the test record back through the pipeline's own write path.
  await payload.update({ collection: 'reports', id: isea.id, draft: true, data: { keywords: isea.keywords, ai_generated: true }, context: { pipeline: true } })
})

await step('publish / unpublish re-index; a pending draft keeps the record out of public search', async () => {
  const flags = async () => (await db(sql`select bool_and(published) as every, bool_or(published) as some from archive_chunks where collection = 'reports' and doc_id = ${String(isea.id)}`))[0]
  const url = `/api/reports/${isea.id}`
  await rest(reviewer, 'PATCH', url, { _status: 'published' })
  await until('chunks published', async () => (await flags()).every === true, 60_000)
  await rest(editor, 'PATCH', `${url}?draft=true`, { credit: isea.credit })
  await until('pending draft hides chunks', async () => (await flags()).some === false, 60_000)
  await rest(reviewer, 'PATCH', url, { _status: 'published' })
  await until('chunks published again', async () => (await flags()).every === true, 60_000)
  await rest(reviewer, 'PATCH', url, { _status: 'draft' })
  await until('unpublish hides chunks', async () => (await flags()).some === false, 60_000)
})

await step('a metadata-only event is indexed as one chunk per locale; deleting it removes them', async () => {
  const { doc } = await rest(editor, 'POST', '/api/events?draft=true', {
    title: 'Step 3 check event',
    description: 'Polar science outreach talk for school students in Goa.',
    event_type: 'school_outreach',
    location: 'Goa',
  })
  try {
    await until('event ready', async () => (await latest('events', doc.id)).processing_state === 'ready', 60_000)
    let chunks = await chunksOf('events', doc.id)
    assert.deepEqual(chunks.map((c) => [c.locale, c.position, c.heading]), [['en', 0, 'Step 3 check event']])
    await rest(editor, 'PATCH', `/api/events/${doc.id}?draft=true&locale=hi`, { title: 'चरण 3 जाँच कार्यक्रम', description: 'गोवा में स्कूली छात्रों के लिए ध्रुवीय विज्ञान वार्ता।' })
    chunks = (await until('Hindi chunk', async () => ((await chunksOf('events', doc.id)).length === 2 ? chunksOf('events', doc.id) : undefined), 60_000)) as Doc[]
    assert.deepEqual(chunks.map((c) => c.locale), ['en', 'hi'])
    assert.match(chunks[1].text, /ध्रुवीय/)
  } finally {
    await rest(editor, 'DELETE', `/api/events/${doc.id}`)
  }
  assert.equal((await chunksOf('events', doc.id)).length, 0)
})

await step('seeded stations and expeditions are indexed and published (pipeline:process --all backfill)', async () => {
  const hits = await db(sql`
    select heading from archive_chunks, websearch_to_tsquery('english', 'Larsemann Hills') q
    where collection = 'stations' and published and tsv @@ q`)
  assert.ok(hits.some((h) => h.heading === 'Bharati'))
  const [{ n }] = await db(sql`select count(distinct doc_id)::int as n from archive_chunks where collection = 'expeditions' and published`)
  assert.equal(n, 39)
})

const out = Object.fromEntries(
  Object.entries(docs).map(([k, d]) => [
    k,
    {
      id: d.id,
      filename: d.filename,
      processing_state: (d.processing_state as string) ?? null,
      page_count: d.page_count,
      ...Object.fromEntries(['summary', 'keywords', 'caption', 'alt', 'tags'].filter((f) => f in d).map((f) => [f, d[f]])),
    },
  ]),
)
mkdirSync('artifacts/step3', { recursive: true })
writeFileSync('artifacts/step3/check-run.json', JSON.stringify({ at: new Date().toISOString(), uploaded, passed, records: out }, null, 2))
console.log(`\n${passed} checks passed. AI outputs: artifacts/step3/check-run.json`)
